"""
This type stub file was generated by pyright.
"""

@<Expression>
@<Expression>
@<Expression>
@<Expression>
class :
	...


@<Expression>
class :
	...


@<Expression>
@<Expression>
@<Expression>
@<Expression>
@<Expression>
class :
	...


@<Expression>
class :
	...


